name: SauceDemoAction

on:
  pull_request:
    branches: [ "master" ]

env:
  USER: ${{ secrets.USER }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Setup browser Chrome
        uses: abhi1693/setup-browser@v0.3.4
        with:
          browser: chrome
          version: latest
      - name: Run TEST
        run: mvn clean test -Duser=$USER -Dpassword=$PASSWORD